spring:
  application:
    name: fragrances
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      schema: content